using System.Threading.Channels;
using Niimbot.Net;
using Niimbot.Net.Framing;

namespace Niimbot.Net.Tests.Fakes;

/// <summary>
/// A no-hardware <see cref="INiimbotTransport"/> for tests (spec §5.1 testing seam). Records every
/// byte the client writes, and delivers canned bytes on read — either pushed directly via
/// <see cref="EnqueueRead"/> or generated by an optional <see cref="Responder"/> that turns each
/// written packet into zero or more reply packets (a scripted printer).
/// </summary>
public sealed class FakeTransport : INiimbotTransport
{
    private readonly Channel<byte[]> _incoming = Channel.CreateUnbounded<byte[]>();
    private readonly PacketAccumulator _writeAccumulator = new();
    private byte[] _leftover = [];
    private int _leftoverPos;

    /// <summary>Every raw byte sequence the client wrote, in order.</summary>
    public List<byte[]> Writes { get; } = [];

    /// <summary>Every fully-framed packet the client wrote, in order.</summary>
    public List<NiimbotPacket> WrittenPackets { get; } = [];

    /// <summary>Optional scripted printer: maps an inbound request packet to reply packet(s).</summary>
    public Func<NiimbotPacket, IEnumerable<NiimbotPacket>>? Responder { get; set; }

    public bool IsConnected { get; private set; }

    public event EventHandler<TransportState>? StateChanged;

    /// <summary>Push raw bytes to be returned by the next read(s).</summary>
    public void EnqueueRead(byte[] data) => _incoming.Writer.TryWrite(data);

    /// <summary>Push a packet (serialized) to be returned by the next read(s).</summary>
    public void EnqueueRead(NiimbotPacket packet) => EnqueueRead(packet.ToBytes());

    public ValueTask ConnectAsync(CancellationToken ct = default)
    {
        IsConnected = true;
        StateChanged?.Invoke(this, TransportState.Connected);
        return ValueTask.CompletedTask;
    }

    public ValueTask DisconnectAsync(CancellationToken ct = default)
    {
        IsConnected = false;
        _incoming.Writer.TryComplete();
        StateChanged?.Invoke(this, TransportState.Disconnected);
        return ValueTask.CompletedTask;
    }

    public ValueTask WriteAsync(ReadOnlyMemory<byte> data, CancellationToken ct = default)
    {
        Writes.Add(data.ToArray());
        _writeAccumulator.Append(data.Span);

        while (_writeAccumulator.TryRead() is { } packet)
        {
            WrittenPackets.Add(packet);
            if (Responder is { } responder)
            {
                foreach (var reply in responder(packet))
                    EnqueueRead(reply);
            }
        }

        return ValueTask.CompletedTask;
    }

    public async ValueTask<int> ReadAsync(Memory<byte> buffer, CancellationToken ct = default)
    {
        if (_leftoverPos >= _leftover.Length)
        {
            try
            {
                _leftover = await _incoming.Reader.ReadAsync(ct).ConfigureAwait(false);
                _leftoverPos = 0;
            }
            catch (ChannelClosedException)
            {
                return 0;
            }
        }

        var available = _leftover.Length - _leftoverPos;
        var n = Math.Min(available, buffer.Length);
        _leftover.AsSpan(_leftoverPos, n).CopyTo(buffer.Span);
        _leftoverPos += n;
        return n;
    }

    public ValueTask DisposeAsync() => DisconnectAsync();
}
